[32m2025-06-18 12:25:54 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - 75626 - LOGS_CAPTURED - Started capturing logs in process (pid: 75626).
[32m2025-06-18 12:25:54 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - 75626 - load_kaggle_data - STEP_START - Started execution of step "load_kaggle_data".
[32m2025-06-18 12:25:54 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - load_kaggle_data - Loading file from: /Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/.tmp_dagster_home_4z1isjms/storage/processed_kaggle_data using PickledObjectFilesystemIOManager...
[32m2025-06-18 12:25:55 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - 75626 - load_kaggle_data - LOADED_INPUT - Loaded input "processed_kaggle_data" using input manager "io_manager", from output "result" of step "processed_kaggle_data"
[32m2025-06-18 12:25:55 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - 75626 - load_kaggle_data - STEP_INPUT - Got input "processed_kaggle_data" of type "[Path]". (Type check passed).
[32m2025-06-18 12:25:55 +0800[0m - dagster - [34mINFO[0m - __ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - load_kaggle_data - Starting Meltano data load (tap-csv to target-bigquery)...
[32m2025-06-18 12:31:54 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 0978f5cc-3708-4f28-b949-88aba3292318 - 75626 - load_kaggle_data - STEP_FAILURE - Execution of step "load_kaggle_data" failed.

dagster._core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 246, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 502, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 90, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 187, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 156, in _yield_compute_results
    for event in iterate_with_context(
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/pipeline_olist/assets.py", line 169, in load_kaggle_data
    result = subprocess.run(
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/subprocess.py", line 2021, in _communicate
    ready = selector.select(timeout)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/anaconda3/envs/dagster_dev/lib/python3.10/site-packages/dagster/_utils/interrupts.py", line 83, in _new_signal_handler
    raise error_cls()
[0m
