[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - 55993 - LOGS_CAPTURED - Started capturing logs in process (pid: 55993).
[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - 55993 - transform_kaggle_data - STEP_START - Started execution of step "transform_kaggle_data".
[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - transform_kaggle_data - Loading file from: /Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/.tmp_dagster_home_etlu7wq6/storage/load_kaggle_data using PickledObjectFilesystemIOManager...
[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - 55993 - transform_kaggle_data - LOADED_INPUT - Loaded input "load_kaggle_data" using input manager "io_manager"
[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - 55993 - transform_kaggle_data - STEP_INPUT - Got input "load_kaggle_data" of type "Any". (Type check passed).
[32m2025-06-17 17:14:57 +0800[0m - dagster - [34mINFO[0m - __ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - transform_kaggle_data - Starting dbt transformations (dbt run)...
[32m2025-06-17 17:15:19 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - transform_kaggle_data - dbt command failed with exit code 1.[0m
[32m2025-06-17 17:15:19 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - transform_kaggle_data - dbt stdout:
[0m09:15:02  Running with dbt=1.9.2
[0m09:15:09  Registered adapter: bigquery=1.9.1
[0m09:15:10  Found 11 models, 27 data tests, 15 sources, 715 macros
[0m09:15:10  
[0m09:15:10  Concurrency: 4 threads (target='dev')
[0m09:15:10  
[0m09:15:14  1 of 11 START sql table model olist_stg.dim_orders_stg ......................... [RUN]
[0m09:15:14  2 of 11 START sql table model olist_stg.dim_product_category_name_translation_stg  [RUN]
[0m09:15:14  3 of 11 START sql table model olist_stg.dim_products_stg ....................... [RUN]
[0m09:15:14  4 of 11 START sql table model olist_stg.dim_sellers_stg ........................ [RUN]
[0m09:15:16  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:a5adf19a-8ee4-42ec-891f-4a733315ca7c&page=queryresults
[0m09:15:16  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:6e9beef0-50c8-4a0d-93f3-36fc628aef31&page=queryresults
[0m09:15:16  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:46be89a9-d3b0-4c33-a4db-0da8e4f493ff&page=queryresults
[0m09:15:16  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:dbbb0d17-a439-4b20-a4d8-dc03f64bfb61&page=queryresults
[0m09:15:16  2 of 11 ERROR creating sql table model olist_stg.dim_product_category_name_translation_stg  [[31mERROR[0m in 1.12s]
[0m09:15:16  1 of 11 ERROR creating sql table model olist_stg.dim_orders_stg ................ [[31mERROR[0m in 1.13s]
[0m09:15:16  4 of 11 ERROR creating sql table model olist_stg.dim_sellers_stg ............... [[31mERROR[0m in 1.13s]
[0m09:15:16  3 of 11 ERROR creating sql table model olist_stg.dim_products_stg .............. [[31mERROR[0m in 1.13s]
[0m09:15:16  5 of 11 START sql table model olist_stg.fact_order_items_stg ................... [RUN]
[0m09:15:16  6 of 11 START sql table model olist_stg.fact_order_payments_stg ................ [RUN]
[0m09:15:16  7 of 11 SKIP relation olist.dim_orders ......................................... [[33mSKIP[0m]
[0m09:15:16  8 of 11 SKIP relation olist.dim_products ....................................... [[33mSKIP[0m]
[0m09:15:16  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:ff48d8be-3ca6-45ff-8bd1-eb7f6fb79da6&page=queryresults
[0m09:15:16  5 of 11 ERROR creating sql table model olist_stg.fact_order_items_stg .......... [[31mERROR[0m in 0.83s]
[0m09:15:16  9 of 11 SKIP relation olist.dim_sellers ........................................ [[33mSKIP[0m]
[0m09:15:17  BigQuery adapter: https://console.cloud.google.com/bigquery?project=sctp-olist&j=bq:US:3ef5801d-cf56-48b9-ad45-866e9afa335d&page=queryresults
[0m09:15:17  6 of 11 ERROR creating sql table model olist_stg.fact_order_payments_stg ....... [[31mERROR[0m in 0.89s]
[0m09:15:17  10 of 11 SKIP relation olist.fact_order_payments ............................... [[33mSKIP[0m]
[0m09:15:17  11 of 11 SKIP relation olist.fact_order_items .................................. [[33mSKIP[0m]
[0m09:15:17  
[0m09:15:17  Finished running 11 table models in 0 hours 0 minutes and 6.47 seconds (6.47s).
[0m09:15:17  
[0m09:15:17  [31mCompleted with 6 errors, 0 partial successes, and 0 warnings:[0m
[0m09:15:17  
[0m09:15:17    Database Error in model dim_product_category_name_translation_stg (models/stg/dim_product_category_name_translation_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.product_category_name_translation: User does not have permission to query table meltano-learn-461903:olist_raw.product_category_name_translation, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/dim_product_category_name_translation_stg.sql
[0m09:15:17  
[0m09:15:17    Database Error in model dim_orders_stg (models/stg/dim_orders_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.olist_orders: User does not have permission to query table meltano-learn-461903:olist_raw.olist_orders, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/dim_orders_stg.sql
[0m09:15:17  
[0m09:15:17    Database Error in model dim_sellers_stg (models/stg/dim_sellers_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.olist_sellers: User does not have permission to query table meltano-learn-461903:olist_raw.olist_sellers, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/dim_sellers_stg.sql
[0m09:15:17  
[0m09:15:17    Database Error in model dim_products_stg (models/stg/dim_products_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.olist_products: User does not have permission to query table meltano-learn-461903:olist_raw.olist_products, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/dim_products_stg.sql
[0m09:15:17  
[0m09:15:17    Database Error in model fact_order_items_stg (models/stg/fact_order_items_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.olist_order_items: User does not have permission to query table meltano-learn-461903:olist_raw.olist_order_items, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/fact_order_items_stg.sql
[0m09:15:17  
[0m09:15:17    Database Error in model fact_order_payments_stg (models/stg/fact_order_payments_stg.sql)
  Access Denied: Table meltano-learn-461903:olist_raw.olist_order_payments: User does not have permission to query table meltano-learn-461903:olist_raw.olist_order_payments, or perhaps it does not exist.
  compiled code at target/run/transform_olist/models/stg/fact_order_payments_stg.sql
[0m09:15:17  
[0m09:15:17  Done. PASS=0 WARN=0 ERROR=6 SKIP=5 TOTAL=11
[0m
[32m2025-06-17 17:15:19 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - transform_kaggle_data - dbt stderr:
/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dbt/adapters/bigquery/connections.py:570: FutureWarning: job_retry must be explicitly set to None if job_id is set.
BigQuery cannot retry a failed job by using the exact
same ID. Setting job_id without explicitly disabling
job_retry will raise an error in the future. To avoid this
warning, either use job_id_prefix instead (preferred) or
set job_retry=None.
  query_job = client.query(
/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dbt/adapters/bigquery/connections.py:570: FutureWarning: job_retry must be explicitly set to None if job_id is set.
BigQuery cannot retry a failed job by using the exact
same ID. Setting job_id without explicitly disabling
job_retry will raise an error in the future. To avoid this
warning, either use job_id_prefix instead (preferred) or
set job_retry=None.
  query_job = client.query(
[0m
[32m2025-06-17 17:15:20 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - fbb0a76d-01cc-4896-ba07-e9be4c92e20b - 55993 - transform_kaggle_data - STEP_FAILURE - Execution of step "transform_kaggle_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "transform_kaggle_data"::

subprocess.CalledProcessError: Command '['dbt', 'run']' returned non-zero exit status 1.

Stack Trace:
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/opt/anaconda3/envs/elt/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/taysk/sctp/Project/SCTP-DSF1-Team5/03 - Code/pipeline-olist/pipeline_olist/assets.py", line 202, in transform_kaggle_data
    result = subprocess.run(
  File "/opt/anaconda3/envs/elt/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
[0m
